exampleOfExceptions.java
Before exception we have to know about Errors.

there are different type of errors.
Compile time error 
Runtime error
Logical error

Compile time error -->Syntactical or syntax error

Logical Error --> bugs --> Logic are wrong are called Logical Error

Runtime Error --> When the program suddenly stop in between. Basically exception is runtime error.

There are two types of statement
1. Normal statement 
2. Critical statement --> Runtime Error Or throws some error

Exception: When executing Java code, different errors can occur: coding errors made by the programmer, errors due to wrong input, or other unforeseeable things.

We need to handle the exceptions.

# If the statement is critical, then to handle the exception we need to try to execute the code.


 TRY:- It's trying to handle the errors in java.

If java tries to execute the code and there will be an error then it will throw the error.


Try will basically try to execute the statements , if everything goes good it will execute the remaining statement.
If something goes wrong, if there is an exception it will execute the catch block.

CATCH: It will catch the error.
you will create an object or you will refer that with an exception class.

If try block is not working then catch will be execute the code.

Catch block will be executed only in case of exception, otherwise catch block will be skipped.