ThrowsExample.java
if the class name is wrong then we got this:


Class Loaded
java.lang.ClassNotFoundException: ThrowsExampe
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:462)
	at java.base/java.lang.Class.forName(Class.java:453)
	at Demo.show(ThrowsExample.java:15)
	at ThrowsExample.main(ThrowsExample.java:31)


This happens because of a typo in the class name, when you accidently mistype the class name  which caused the ClassNotFoundException.